version: '3.8'

services:
  mentally-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentally-container
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
