// Legal Disclaimer and Terms of Service Component
export const Legal = () => {
  return `
    <div class="card">
      <h2 style="font-family: 'Orbitron', sans-serif; color: #ff3366; text-shadow: 0 0 20px #ff3366;">LEGAL NOTICE & AI DISCLAIMER</h2>
      
      <div style="line-height: 1.8; color: #aaa; margin-top: 1rem;">
        <h3 style="font-family: 'Orbitron', sans-serif; color: #fff; margin-top: 2rem; margin-bottom: 0.5rem;">1. GENERAL DISCLAIMER</h3>
        <p>
          This application, "Thought GPS" (hereinafter referred to as the "Service"), is provided on an "as is" and "as available" basis without any warranties of any kind, express or implied. The Service is for personal cognitive modeling, research, and organizational purposes only.
        </p>

        <h3 style="font-family: 'Orbitron', sans-serif; color: #fff; margin-top: 2rem; margin-bottom: 0.5rem;">2. AI & AUTOMATION USAGE</h3>
        <p>
          The Service utilizes third-party artificial intelligence models, automated routing (including but not limited to OmniRoute, OpenAI, Anthropic, and Groq), and vector memory graphs to categorize, analyze, and decay thoughts. 
        </p>
        <p style="color: #ff3366; font-weight: bold;">
          IMPORTANT NOTICE ON AI GENERATED CONTENT: Artificial intelligence models are prone to "hallucinations" (generating false, incorrect, or inaccurate details) and may encounter processing or logic errors. All generated text, classifications, cognitive summaries, and system recommendations must be carefully reviewed. Users are expected to re-read, re-evaluate, and verify all output answers before making choices or acting upon them. The final choice, configuration, and trust placed in the system rest entirely with the user.
        </p>
        <p>
          The outputs generated by the AI models do not represent the views of the platform or its operators. Users are solely responsible for actions taken based on automated thoughts, reminders, commitment checks, or notifications.
        </p>

        <h3 style="font-family: 'Orbitron', sans-serif; color: #fff; margin-top: 2rem; margin-bottom: 0.5rem;">3. PRIVACY & SECURE KEY STORAGE</h3>
        <p>
          All configured API keys are stored server-side using industry-standard AES-256 encryption. Key credentials are used strictly for communicating with backend providers on your behalf.
          Data is stored in isolated PostgreSQL database scopes. While security measures are implemented, no storage mechanism is 100% secure. You agree to hold the Service harmless for any data breaches.
        </p>

        <h3 style="font-family: 'Orbitron', sans-serif; color: #fff; margin-top: 2rem; margin-bottom: 0.5rem;">4. USER RESPONSIBILITY & COMPLIANCE</h3>
        <p>
          You agree to comply with all applicable local, national, and international laws when using the Service. The Service must not be used for tracking illegal activities, harassment, sending unauthorized notifications/messages to witnesses without consent, or violating intellectual property rights.
        </p>

        <h3 style="font-family: 'Orbitron', sans-serif; color: #fff; margin-top: 2rem; margin-bottom: 0.5rem;">5. LIMITATION OF LIABILITY</h3>
        <p>
          In no event shall the Service, its creators, or affiliates be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use of or inability to use the platform.
        </p>
      </div>
      
      <div style="margin-top: 3rem; text-align: center;">
        <button class="btn btn-primary" onclick="showPage('home')">RETURN TO HOME</button>
      </div>
    </div>
  `;
};
